{{- $backendJwtSecret := .Values.backendJwtSecret | required ".Values.backendJwtSecret is required." -}}

---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: {{ .Release.Name }}-refresh
    labels:
        app.kubernetes.io/component: {{ .Release.Name }}-refresh
        app.kubernetes.io/instance: {{ .Release.Name }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app.kubernetes.io/component: {{ .Release.Name }}-refresh
                app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.podAnnotations }}
            annotations:
{{ toYaml . | nindent 16 }}
{{- end }}
        spec:
{{- if .Values.priorityClassName }}
            priorityClassName: {{ .Values.priorityClassName }}
{{- end }}
{{- with .Values.image.pullSecrets }}
            imagePullSecrets:
{{- toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.tolerations }}
            tolerations:
{{- toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.affinity }}
            affinity:
{{- toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.nodeSelector }}
            nodeSelector:
{{- toYaml . | nindent 16 }}
{{- end }}
            restartPolicy: Always

            containers:
                -   name: {{ .Release.Name }}-refresh
                    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    args:
{{- with .Values.refresh.debugPort }}
                        - "--inspect={{ . }}"
{{- end }}
                        - "scrapoxy.js"
                        - "start"
                        - "-r"
                    ports:
                        -   name: probe
                            containerPort: 8887
                            protocol: TCP
{{- with .Values.refresh.debugPort }}
                        -   name: debug
                            containerPort: {{ . }}
                            protocol: TCP
{{- end }}
                    livenessProbe:
                        httpGet:
                            path: /
                            port: probe
                    readinessProbe:
                        httpGet:
                            path: /
                            port: probe
                    resources:
                        {{- toYaml .Values.refresh.resources | nindent 24 }}
                    env:
                        -   name: NODE_ENV
                            value: "production"
                        -   name: COMMANDER_URL
                            value: "http://{{ .Release.Name }}-commander:{{ .Values.commander.port }}/api"
                        -   name: BACKEND_JWT_SECRET
                            value: {{ $backendJwtSecret }}
